### ISSUE TITLE
local variable error

### ISSUE THREAD

**Issue by Blackhawk2165** [RocketDepartment/twitter-analytics-parser#1]
Hello,

I am getting this error when running the python script:

Traceback (most recent call last):
    File "twitter_metrics.py", line 73, in <module>
       main()
   File "twitter_metrics.py", line 53, in main
       data = [top_retweets, top_replies, top_favs]
UnboundLocalError: local variable 'top_retweets' referenced before assignment

I looked through the code and I didn't see any errors so I'm confused as to why this error is coming is there something wrong with my .csv?

Thanks,
Austin

**Comment by efletch** [comment]
Hi Austin,

At first glance I don't see anything wrong it the code either. I downloaded a new csv from analytics.twitter.com to see if they modified their columns but I didn't see any errors. There could be something wrong with your csv. Could you upload it somewhere and share a link so I can take a look? 

Thanks,
Emma

**Comment by efletch** [comment]
Here is copy of a csv that should work with the parser, at least it just worked on my machine :)

http://goo.gl/fxZBxz

**Comment by Blackhawk2165** [comment]
I shared the file with you on google drive. I added the promoted (field name) to the .csv like you have on yours but it still isn't working. Your csv works when I run it on my machine but my csv just isn't working. You do have some extra fields in yours that I don't but I'm not sure what that has to do with the retweet problem. 

Thanks for your help,
Austin

**Comment by Blackhawk2165** [comment]
Turns out my Marketing person deleted columns out of the csv before sending it to me so that was the issue thanks for your help
